### PR TITLE
Cuterdio added

### PR DESCRIPTION
**Pull request by Suplanus**

### CODE REVIEW

**Comment by InquisitorJax** [comment]
conflicted

**Comment by Suplanus** [comment]
Thanks!
Yes, we have to push the Xamarin apps 🚀

**Comment by InquisitorJax** [comment]
yikes - I only saw the huge images - is there a way we can make them smaller in a single row like the others?

**Comment by Suplanus** [comment]
Oh sorry, I will fix that.  
GitHub not showing up the downsize.

**Pull request merged**
